Cover each class of ogci library with simple tests
ops-guru/ogci pull request #5
Opened 2017-10-12 15:31 UTC by alitet01

## Cover each class of ogci library with simple tests
Use simple tests, one method of each class
- job: should point at groovy file `jobs/tests/all.groovy`
- tests:
    - test scripts should reside under `jobs/tests`
    - naming convention: `test${component}Simple.groovy`

2017-10-14 16:29 UTC, mvk requested changes
@alitet01 just rename as I request, and you can merge.

2017-10-14 16:29 UTC, mvk commented on jobs/tests/all.groovy
> +    def groovies = sh([
@alitet01 maybe rename from here downwards:
```
groovies -> testFileNamesOutput
grooviesArr -> testFileNamesArr
groovyPath -> testFileName
```

2017-10-15 10:44 UTC, alitet01 commented
надо переговорить, когда это удобно сделать?
Виктор


On Sat, Oct 14, 2017 at 7:29 PM, Max Kovgan <notifications@github.com>
wrote:

> *@mvk* requested changes on this pull request.
>
> @alitet01 <https://github.com/alitet01> just rename as I request, and you
> can merge.
> ------------------------------
>
> In jobs/tests/all.groovy
> <https://github.com/ops-guru/ogci/pull/5#discussion_r144697639>:
>
> > +                        [name: "${sha1}"]
> +                ],
> +                doGenerateSubmoduleConfigurations: false,
> +                extensions: [],
> +                submoduleCfg: [],
> +                userRemoteConfigs: [
> +                        [
> +                                credentialsId: gitCredentialsId,
> +                                url: gitSshUrl,
> +                                name: 'origin',
> +                                refspec: "+refs/heads/*:refs/remotes/origin/* +refs/pull/*:refs/remotes/origin/pr/*"
> +                        ]
> +                ]
> +        ])
> +    }
> +    def groovies = sh([
>
> @alitet01 <https://github.com/alitet01> maybe rename from here downwards:
>
> groovies -> testFileNamesOutput
> grooviesArr -> testFileNamesArr
> groovyPath -> testFileName
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/ops-guru/ogci/pull/5#pullrequestreview-69395862>, or mute
> the thread
> <https://github.com/notifications/unsubscribe-auth/Aes8Al3x73g2LK_O11yYr7nZkYQqOaAYks5ssOFVgaJpZM4P3MpY>
> .
>

2017-10-19 20:01 UTC, alitet01 commented
waiting for approval

2017-10-20 09:01 UTC, mvk requested changes
@alitet01 please consolidate all the changes you've tested into this branch.

Thanks.

2017-10-20 10:26 UTC, closed without merging